apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: hermesdaviskas/knauf.maestro_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.{ts,js}"
            dest: .
